# Generated by Django 4.2.1 on 2023-06-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactform_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contacto',
        ),
        migrations.RemoveField(
            model_name='newsstate',
            name='feedback',
        ),
        migrations.AddField(
            model_name='news',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
