# Generated by Django 4.2.1 on 2023-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_contactform_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
